Locals = {

    OnlyAdmin = 'This command is for admin use only',

    Main = {
        AdminMenu = ' Admin menu',

        Actions = ' Actions',
        Self = 'Self',
        Player = 'Player',
        Vehicle = 'Vehicle',
        Server = 'Server',

        Message = 'Message',
        Empty = 'Your input is empty',
        ID = 'ID',
    },
    Self = {
        SelfMenu = 'Self Menu',
        ReviveMe = 'Revive me',
        RevivedSelf = 'You have revived yourself',
    
        HealMe = 'self heal',
        HealSelf = 'You have held yourself',
    
        ArmorMe = 'Give armor',
        ArmorSelf = 'You have given yourself armor',
    
        KillMe = 'Kill self',
        KillSelf = 'you killed yourself',

        WeaponMe = 'Give weapon',
        WeaponQuickSelection = 'Quick selection',
        WeaponDsec = 'Quickly give weapon',
        WeaponAdd = 'Add weapon',
        WeaponName = 'Spawn name',
        WeaponWhich = 'Which weapon',
        WeaponAmmu = 'Ammunition',
        WeaponAmmuDesc = 'How much ammunition',
        WeaponEnterNumber = 'You must enter a valid number',
        WeaponInfo = 'Weapon info',
        WeaponWithESX = 'Not with ESX?',

        ItemMe = 'Give item',
        ItemQuickSelection = 'Quick selection',
        ItemDesc = 'Quickly give item',
        ItemName = 'Spawn name',
        ItemWeight = ' Weight',
        ItemCanRemove = 'Can remove',
        ItemAdd = 'Add item',
        ItemCount = 'Count',
        ItemWhich = 'Which item',
        ItemMuch = 'How much items',
        ItemEnterNumber = 'You must enter a valid number',
        ItemAddCount = 'Add count',

        MoneyMe = 'Give money',
        MoneyMeBank ='Give money bank',
        MoneyAdd = 'Add money',
        Money = 'Money',
        MoneyMuch = 'how much money',
        MoneyEnterNumber = 'You must enter a valid number',

        NoclipMe = 'Noclip',

        Webhooks = {
            RevivedSelf = 'An admin has revived himself',
            HealedSelf = 'An admin has healed himself',
            ArmorSelf = 'An admin has given himself armor',
            KilledSelf = 'An admin killed himself',
        }
    },
    
    Player = {
        KickPlayer = 'Kick player',
        IDs = 'Steamname/ID/Name',
        EnterIDs = 'Enter a Steam name, ID or the name of a player here',

        AtLeast3 = 'you must enter at least 3 characters',
        NoPlayerFound = 'No player was found',
        PlayerFound = '%s players were found',

        Search = 'Search',
        SearchPlayer = 'Search player',
        Refresh = 'Refresh',
        RefreshList = 'Refresh list',
        Steam = 'Steam',
        Job = 'Job',
        Group = 'Group',

        Ban = 'Ban',
        BanPlayer = 'Ban player',
        Inventory = 'Inventory',
        PlayerInventory = 'Player Inventory',
        Weapon = 'Weapons',
        PlayerWeapons = 'Player weapons',
        TakeScreenshot = 'Take screenshot',
        PlayerScreenshot = 'Take a screenshot from a player',
        JobMenu = 'Job menu',
        PlayerJobMenu = 'Player job menu',
        SendMsg = 'Send message',
        PlayerSendMsg = 'Send player a message',
        Kick = 'Kick Player',
        PlayerKick = 'Kick a player from the server',
        Kill = 'Kill player',
        PlayerKill = 'Kill player',
        Armor = 'Give armor',
        PlayerArmor = 'Give a player armor',
        Money = 'Give money',
        PlayerMoney = 'Give a player money',

        -- Ban Menu
        BanMenu = 'Ban menu',
        SpecificBan = 'Specific ban', 
        SpecificBanDesc = 'Ban players after certain days',
        BanHour = '1 hour',
        BanHourDesc = 'for 1 hour',
        BanDay = '1 day',
        BanDayDesc = 'for 1 day',
        BanWeek = '1 week',
        BanWeekDesc = 'for 1 week',
        BanPerm = 'Ban permanent',
        BanPermDesc = 'Ban for permanent',
        Reason = 'Reason',
        ReasonDesc = 'Ban reason',
        DateInput = 'Date input',

        -- Money Menu
        MoneyMenu = 'Money menu',
        MoneyName = 'Money',
        MoneyBank ='Give money bank',
        MoneyAdd = 'Add money',
        MoneyMuch = 'how much money',
        MoneyEnterNumber = 'You must enter a valid number',

        -- Weapon
        WeaponAddPlayer = 'Add a weapon to a player',
        WeaponGive = 'Give weapon',
        WeaponDelAll = 'Delete all weapons',
        WeaponDelAllDesc = 'Delete all weapons from a player',
        WeaponAmmu = 'Ammunition',
        WeaponTintIndex = 'Tint Index',
        WeaponAdd = 'Add weapon',
        WeaponQuickSelection = 'Quick selection',
        WeaponDsec = 'Quickly give weapon',
        WeaponAmmuDesc = 'How much ammunition',
        WeaponInfo = 'Weapon info',
        WeaponEnterNumber = 'You must enter a valid number',
        WeaponDelAllSure = 'Are you sure you want to remove all the weapons from the player',
        WeaponAdjustAmmunition = 'Adjust ammunition',
        WeaponRemove = 'Remove weapon',
        WeaponRemoveDesc = 'Remove this weapon',
        WeaponAdjustComponent = 'Adjust components',
        WeaponHasComponent = 'Player has so many components',
        WeaponNoComponent = 'The player has no components',
        ComponentMenu = 'Waffen components Menu',
        WeaponComponent = 'Component',
        WeaponComponentRemove = 'Remove Component',

        -- Kick
        KickDesc = 'Message displayed on kick',

        -- Message
        SendMessage = 'Send message',
        PrivateMessage = 'Privat message',

        -- Job
        JobName = 'Job name',
        JobGrade = 'Grade',
        JobChange = 'Change job',
        JobReset = 'Reset job',
        JobResetDesc = 'Set the player job to default',

        -- Item
        Item = 'item',
        ItemAdd = 'Add item',
        ItemAddDesc = 'Add an item to a player',
        ItemName = 'Item name',
        ItemCount = 'Count',
        ItemMuch = 'How much items',
        ItemDellAll = 'Delete all items',
        ItemDellAllDesc = 'delete all items from one player',
        ItemDelAllDia = 'Sure you want to remove all items from the player?',
        ItemMax = 'Max Weight',
        ItemOnlySingle = 'Remove only single item',
        ItemOnlySingleDesc = 'remove only specific number',
        ItemRemove = 'Remove item',
    },

    Vehicle = {
        Menu = 'Vehicle Menu',
        DelOne = 'Delete one vehicle',
        DelRadius = 'Delete vehicle radius',
        Spawn = 'Spawn vehicle',
        GivePlayer = 'Give vehicle to player',
        DelPlayer = 'Delete vehicle from player',

        DelVehicle = 'Delete vehicle',
        Plate = 'Plate',
        Vehicleplate = 'Vehicle plate',
        InstantDelete = 'Delete vehicle instant',

        -- Spawn
        SpawnVehicle = 'Spawn vehicle',
        GiveVehicle = 'Give vehicle',
        GiveEnterID = 'Enter player ID',
        SpawnName = 'Spawnname',
        SpawnNameDesc = 'Enter the spawnname from the vehicle',
        PlateDesc = 'Enter the plate (not needed)',
        RandomPlate = 'Random plate',
        PrimaryColor = 'Primary color',
        SecondaryColor = 'Secondary color',
        SaveInDB = 'Save in DB?',
        noTExistent = 'non-existent spawnname',

        -- Del
        NoVehNear = 'There is no vehicle nearby',
        DelNear = 'You have deleted the vehicle near you',

        DelInRadius = 'Delete vehicles in radius',
        Radius = 'Radius',
        RadiusDesc = 'In how many meters should be removed all vehicles',
        Delsuccess  = 'You have deleted the vehicles within %s radius', -- %s is how many vehicles (int)
    },

    ServerMenu = {
        Menu = 'Server Menu',
        SendAnnounce = 'Send Announce',
        ReviveAll = 'Revive all',
        ReviveAllDesc = 'Are you sure you want to revive every player?',
        DeleteAllVeh = 'Delete all vehicles',
        DeleteAllVehDesc = 'Are you sure you want to delete all vehicles?',
        AnnounceMSG = 'Announce message',
        AnnounceMSGDesc = 'All players get this message',

        -- Banlist menu
        Banlist = 'Banlist',
        BanlistDesc = 'You see all banned players',
        NoBannedPlayers = 'There are no banned players',
        Reason = 'Reason',
        UnbanTime = 'Time till unban',
        UnbanPlayer = 'Do you want to unban this player',
        Identifier = 'Identifier',
        Name = 'Name',
        BanTime = 'Bantime',
    },

    Server = {
        NoGroup = 'You were kicked because you triggered an event, which you are not allowed to do.',
        CantCarry = 'you cant carry that item',
        VehicleDoenstExist = 'The vehicle doenst exist',
        IDDoenstExist = 'The ID doenst exist',

        -- Webhook
        Data = 'Data',
        PlayerInfo = ' Player info',
        AdminInfo = 'Admin info',

        AdminKillPlayer = 'An admin has killed another player via the admin menu',
        AdminArmorPlayr = 'An admin has given another player Armor',
        AdminRemoveCompPlayer = 'An admin has removed a weapon component from a player',
        AdminRemoveCompPlayerNotifyAdmin = 'The player does not have this component',
        AdminRemoveCompPlayerNotifyTarget = 'An admin has removed one weapons component',
        AdminKickPlayer = 'An admin has kicked a player',
        AdminKickPlayerAdmin = 'This player is not online',
        AdminGiveWeaponPlayer = 'An admin has given a weapon to another player',
        AdminGiveWeaponPlayerAdmin = 'The player already has this weapon',
        AdminGiveWeaponPlayerTarget = 'An admin gave you a gun',
        AdminUpdateAmmuPlayer = 'An admin has updated the ammunition from a player of his weapon',
        AdminRemoveWeapon = 'An admin has removed a weapon from a player',
        AdminRemoveWeaponTarget = 'An admin has taken away a weapon from you',
        AdminPrivateMSG = 'An admin has sent a message to another player',
        AdminPrivateMSGAdmin = 'Message was sent',
        AdminUpdateJobPlayer = 'An admin has changed the job of a player',
        AdminUpdateJobPlayerTarget = 'Your job got reset',
        AdminUpdateJobPlayerAdmin = 'Your specified job does not exist',
        AdminRemoveAllWeapon = 'An admin has removed all weapons from a player',
        AdminRemoveAllWeaponTarget = 'You have all your weapons removed',
        AdminRemoveAllWeaponAdmin = 'The player has no weapons',
        AdminRemoveAllItem = 'An admin has removed the whole inventory',
        AdminRemoveAllItemTarget = 'You have been removed all items',
        AdminRemoveAllItemAdmin = 'The player has no items in the inventory',
        AdminGiveMoney = 'An admin gave himself money',
        AdminGiveMoneyAdmin = 'you gave yourself %s$',
        AdminGiveMoneyPlayer = 'An admin gave a player money',
        AdminGiveMoneyPlayerTarget = 'your are given %s$',
        AdminGiveItem = 'An admin gave himself an item',
        AdminDelAllVehicles = 'An admin deleted all vehicles',
        AdminDelAllVehiclesAdmin = 'You deleted %s Vehicles',
        AdminRemoveItemPlayer = 'An admin has removed a number of items from a player',
        AdminRemoveAlltemPlayer = 'One admin has removed all from one player from one item',
        AdminRemoveVehiclePlayer = 'An admin has removed a player vehicle',
        AdminRemoveVehiclePlayerTarget = 'A vehicle of yours has been removed: %s',
        AdminGiveVehicle = 'An admin gave himself a vehicle',
        AdminGiveVehiclePlayer = 'An admin gave a player a veihlce',
        AdminGiveVehiclePlayerAdmin = 'You have given a vehicle to a player',
        AdminGiveVehiclePlayerTarget = 'You were given a vehicle',
        AdminTookScreenshot = 'An admin has taken a screenshot from another player',
        AdminAnnounce = 'An admin has sent an announce',
        AdminRevivedAll = 'An admin has revived all players',
        AdminGiveWeaponSelf = 'an admin gave him self a weapon',
        PlayerInjection = 'a player has used an event or function he is not allowed to use (probably trigger injection)',
        PlayerGotBanned = 'A player got banned',
        PlayerGotUnbanned = 'A player got unbanned',

        ServerKick = 'Server kick',
    },

    Ban = {
        Banned = 'You got banned from the server',
        BannedPerma = 'You got banned permanent from this server',
        Reason = 'Reason',
        Discord = 'The support discord',
        Date = 'Date',
        Time = 'Time',
        PlayerCantBeBanned = 'This player cant be banned',
        BanGetCheckeck = 'The Banlist get checked right now :)',
        DiscordLink = 'https://discord.gg/123',
        BanExpired = 'Your ban is expired. You get unbanned',
        TimeRemaining = 'Time remaining',
        Year = 'Year',
        Month = 'Month',
        Day = 'Day',
        Hour = 'Hour',
        Min = 'Minutes',
        Sec = 'Seconds',
        PlayerDoenstExist = 'This Player doenst exist',
        PlayerUnbanned = 'player is unbanned',
        PlayerNotBanned = 'The player is not banned',
        InvalidIdentifierFormat = 'Invalid identifier format',
        DontActive = 'The ban menu is disabled',
    }
}